name: Sync and Inject Custom Rules

on:
  schedule:
    # 每天 UTC 时间 23:29 (北京时间早上 7:29) 自动执行 因为GitHub action的延时，所以提前了时间设定
    - cron: '29 23 * * *'
  workflow_dispatch: # 允许随时在网页上手动触发

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4
        # 默认浅克隆，速度更快

      - name: Download latest rules from Upstream
        run: |
          # 直接下载原作者 release 分支的最新的 Raw 文件覆盖本地
          wget -O sr_top500_banlist.conf https://raw.githubusercontent.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever/release/sr_top500_banlist.conf

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run Injection Script
        env:
          PUSHDEER_KEY: ${{ secrets.PUSHDEER_KEY }}
        run: python inject_rules.py

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add sr_top500_banlist.conf
          
          # 检查文件是否有变动，如果有变动才执行 commit
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto sync and inject custom rules"
          
          # 推送到你当前所在的活动分支
          git push origin HEAD
